<?php

declare(strict_types=1);

namespace App\Traits\Handler;

use App\Enums\ModulesPrefix;
use App\Exceptions\Handler;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Illuminate\Support\Str;
use Modules\Mobile\Exceptions\BaseException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Throwable;

class ModulesHandler extends Handler
{
    /**
     * @param $request
     * @param Throwable $e
     * @return JsonResponse|RedirectResponse|Response|\Symfony\Component\HttpFoundation\Response
     * @throws Throwable
     */
    public function render($request, Throwable $e): JsonResponse|RedirectResponse|Response|\Symfony\Component\HttpFoundation\Response
    {
        // web
        if ($request->is(ModulesPrefix::Administrator->value.'/*')) {
            return match (true) {
                /* @phpstan-ignore-next-line */
                $e instanceof NotFoundHttpException => response()->view(Str::lower(ModulesPrefix::Administrator->name).'::error.404'),
                default => parent::render($request, $e),
            };
        }
        // api
        if ($request->wantsJson() || $request->is(ModulesPrefix::Mobile->value.'/*')) {
            return match (true) {
                $e instanceof AuthenticationException => throw new BaseException($e),
                default => parent::render($request, $e),
            };
        }

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
